### ISSUE TITLE
Connection to host '10.11.99.1' not possible, aborting...

### ISSUE THREAD

**Issue by emilBeBri** [mosauter/remarkable_scripts#1]
Hi thank you for making this - I get in trouble fairly quickly, though, when I do either of these:

```


remarkable2pdf 'mysearch'  --host 10.11.99.1
remarkable2pdf 'mysearch'  --host root@10.11.99.1

```

I get:

```
Connection to host '10.11.99.1' not possible, aborting...
```

I can ssh into the tablet fine by doing:

```

ssh root@10.11.99.1

```

Here I have to enter this:

```

Enter passphrase for key '/home/emil/.ssh/id_rsa':
root@10.11.99.1's password:

```
I have the passphrase empty. The root psw is the one provided in the remarkable GUI.

I'm sort of learning by doing, so if you could help me understand what I'm doing wrong here I would appreciate it!

**Comment by mosauter** [comment]
> I can ssh into the tablet fine by doing:
> 
> ```
> ssh root@10.11.99.1
> ```
> 
> Here I have to enter this:
> 
> ```
> Enter passphrase for key '/home/emil/.ssh/id_rsa':
> root@10.11.99.1's password:
> ```
> 
> I have the passphrase empty. The root psw is the one provided in the remarkable GUI.

So this seems to me, that you have generated an ssh-key (i.e. `/home/emil/.ssh/id_rsa`), but the tablet doesn't recognize it or doesn't allow it as an authentication mechanism.

That's why you have to provide the tablet-password then afterwards. Strictly speaking the password for the key in this case "should" be irrelevant, as the key is irrelevant.

This could honestly be because of a lot of reasons. 

Depending on how familiar you are with `ssh` in general you might have a `sshconfig`. Generally this would be a file at `~/.ssh/config`.

I would recommend that you add an entry in there, as there are a couple of options you have to set with the modern variant of the tablet.

My entry looks like this:

```
Host local-remarkable
    HostName 10.11.99.1
    User root
    StrictHostKeyChecking no
    IdentitiesOnly yes
    IdentityFile ~/.ssh/remarkable
    HostKeyAlgorithms +ssh-rsa
    PubkeyAcceptedKeyTypes +ssh-rsa
```

You would need to adapt the `IdentityFile` to an absolute path to your specific key. Afterwards you can than always only run:

```
ssh local-remarkable
```

Additionally you have to tell your tablet to accept the login with your key. [The remarkablewiki has some help for that if you want more details (also on the host entry) here](https://remarkablewiki.com/tech/ssh?s[]=ssh). The short gist of it is to run:

```
ssh-copy-id -i ~/path/to/your/ssh/key root@10.11.99.1
```
... once and afterwards it should run fine without needing the password for a login. Afterwards the scripts also should work fine again.

On another note though the scripts are currently working with `rmrl` as a renderer library which has not been updated yet to the new notebook format that came with the big v3 system update. 

I'm working on an alternative but this could still take some time. So don't expect everything to work out of the box.

**Comment by emilBeBri** [comment]
nice thank you for the help, I'll try it out one of the coming days. I'm totally new to ssh and only learned it because I wanted access to the rm2 and transfer files, so there seems to be some learning for me here.

 I haven't updated to 3.0.0 thank God, since I want to keep dvi hacks.

**Comment by emilBeBri** [comment]
Ok that worked. Removed   

~/.ssh/the id_rsa  

and followed the wiki entry for pwd-less entry worked.
